version: "2"
services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./dist:/server/dist
    ports:
      - "9999:9999"
      - "9222:9222"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:3.2-alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    network_mode: host
